/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../vite.config`; params?: Router.UnknownInputParams; } | { pathname: `/../src/constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/../src/store/navStore`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/icons/TabIcons`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/BottomNav`; params?: Router.UnknownInputParams; } | { pathname: `/../src/layouts/RootLayout`; params?: Router.UnknownInputParams; } | { pathname: `/../src/views/LogView`; params?: Router.UnknownInputParams; } | { pathname: `/../src/views/PlanView`; params?: Router.UnknownInputParams; } | { pathname: `/../src/views/ProgressionView`; params?: Router.UnknownInputParams; } | { pathname: `/../src/views/ProfileView`; params?: Router.UnknownInputParams; } | { pathname: `/../src/router`; params?: Router.UnknownInputParams; } | { pathname: `/../src/main`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/log` | `/log`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/plan` | `/plan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/progression` | `/progression`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../vite.config`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/constants/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/store/navStore`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/icons/TabIcons`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/BottomNav`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/layouts/RootLayout`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/views/LogView`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/views/PlanView`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/views/ProgressionView`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/views/ProfileView`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/router`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/main`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/log` | `/log`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/plan` | `/plan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/progression` | `/progression`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../vite.config${`?${string}` | `#${string}` | ''}` | `/../src/constants/theme${`?${string}` | `#${string}` | ''}` | `/../src/store/navStore${`?${string}` | `#${string}` | ''}` | `/../src/components/icons/TabIcons${`?${string}` | `#${string}` | ''}` | `/../src/components/BottomNav${`?${string}` | `#${string}` | ''}` | `/../src/layouts/RootLayout${`?${string}` | `#${string}` | ''}` | `/../src/views/LogView${`?${string}` | `#${string}` | ''}` | `/../src/views/PlanView${`?${string}` | `#${string}` | ''}` | `/../src/views/ProgressionView${`?${string}` | `#${string}` | ''}` | `/../src/views/ProfileView${`?${string}` | `#${string}` | ''}` | `/../src/router${`?${string}` | `#${string}` | ''}` | `/../src/main${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/log${`?${string}` | `#${string}` | ''}` | `/log${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/plan${`?${string}` | `#${string}` | ''}` | `/plan${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/progression${`?${string}` | `#${string}` | ''}` | `/progression${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../vite.config`; params?: Router.UnknownInputParams; } | { pathname: `/../src/constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/../src/store/navStore`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/icons/TabIcons`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/BottomNav`; params?: Router.UnknownInputParams; } | { pathname: `/../src/layouts/RootLayout`; params?: Router.UnknownInputParams; } | { pathname: `/../src/views/LogView`; params?: Router.UnknownInputParams; } | { pathname: `/../src/views/PlanView`; params?: Router.UnknownInputParams; } | { pathname: `/../src/views/ProgressionView`; params?: Router.UnknownInputParams; } | { pathname: `/../src/views/ProfileView`; params?: Router.UnknownInputParams; } | { pathname: `/../src/router`; params?: Router.UnknownInputParams; } | { pathname: `/../src/main`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/log` | `/log`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/plan` | `/plan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/progression` | `/progression`; params?: Router.UnknownInputParams; };
    }
  }
}
